# Node docker image on which this would be run
image: node:8.10.0

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy_production

# Job 2:
# Deploy to staging
Production:
  image: ruby:latest
  only:
    - master
  stage: deploy_production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=lasellplus --api-key=8f44ef09-2723-42e0-9da6-80f44a3f48b7
