stages:
  - dependencies
  - test
  - build
  - deploy

dependencies_job:
  stage: dependencies
  tags:
    - node
  script:
    - npm install
    - echo dependencies_passed!

test_job:
  stage: test
  tags:
    - node
  script:
    - npm install
    - npm run test
    - echo test_passed!

build_job:
  stage: build
  tags:
    - node
  script:
    - npm install
    - npm run test
    - npm run build
    - echo build_passed!

